name: Experience Builder
type: Demo
description: A demonstration of the next-generation Experience Builder for Drupal.
install:
  - experience_builder
config:
  import:
    experience_builder:
      - image.style.xb_avatar
  actions:
    # Disable all components XB generated during installation. Some components
    # have two- or three-part identifiers, so we need to disable those
    # separately.
    experience_builder.component.*.*:
      disable: []
    experience_builder.component.*.*.*:
      disable: []
    # Re-enable the components provided by Drupal CMS.
    experience_builder.component.sdc.drupal_cms_olivero.*:
      enable: []
