name: Experience Builder Demo
type: Demo
description: A demonstration of the next-generation Experience Builder for Drupal.
recipes:
  - starshot_demo_content
install:
  - block
  - experience_builder
  - gin
  - navigation_top_bar
  - starshot_demo
config:
  import:
    experience_builder:
      - image.style.xb_avatar
      - experience_builder.xb_asset_library.global
  actions:
    # Disable all components XB generated during installation. Some components
    # have two- or three-part identifiers, so we need to disable those
    # separately.
    experience_builder.component.*.*:
      disable: []
    experience_builder.component.*.*.*:
      disable: []
    # Re-enable the components provided by Drupal CMS.
    experience_builder.component.sdc.drupal_cms_olivero.*:
      enable: []
    gin.settings:
      simpleConfigUpdate:
        secondary_toolbar_frontend: false
    system.performance:
      simpleConfigUpdate:
        css.preprocess: false
        js.preprocess: false
    system.theme:
      simpleConfigUpdate:
        default: starshot_demo
      simpleConfigUpdate:
        admin: gin
