name: Experience Builder
type: Demo
description: A demonstration of the next-generation Experience Builder for Drupal.
recipes:
  - core/recipes/basic_block_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - starshot_demo_recipe_blocks
  - starshot_demo_recipe_files
  - starshot_demo_recipe_media
  - starshot_demo_recipe_menus
install:
  - block
  - experience_builder
  - gin
  - navigation_top_bar
  - project_browser
  - starshot_demo
config:
  import:
    experience_builder:
      - image.style.xb_avatar
  actions:
    # Disable all components XB generated during installation. Some components
    # have two- or three-part identifiers, so we need to disable those
    # separately.
    experience_builder.component.*.*:
      disable: []
    experience_builder.component.*.*.*:
      disable: []
    # Re-enable the components provided by Drupal CMS.
    experience_builder.component.sdc.drupal_cms_olivero.*:
      enable: []
    block.block.drupal_cms_olivero_breadcrumbs:
      disable: []
    block.block.drupal_cms_olivero_page_title:
      disable: []
    gin.settings:
      simpleConfigUpdate:
        secondary_toolbar_frontend: false
    project_browser.admin_settings:
      simpleConfigUpdate:
        enabled_sources:
          - drupalorg_jsonapi
    system.theme:
      simpleConfigUpdate:
        default: starshot_demo
